"use client";

import { Building2, Globe2, Search, Trash2 } from "lucide-react";
import type { FormEvent, ReactNode } from "react";
import type { ExcludedStock, StrategyMarket } from "../strategy-settings";
import { StrategyRuntimeStatus } from "./StrategyRuntimeStatus";

export function MarketTabs({ value, enabledMarkets, onChange }: { value: StrategyMarket; enabledMarkets: StrategyMarket[]; onChange: (market: StrategyMarket) => void }) {
  return <div className="grid max-w-sm grid-cols-2 rounded-xl border border-slate-200 bg-slate-100 p-1" role="tablist" aria-label="전략 시장 선택">
    {(["domestic", "overseas"] as const).map((market) => { const enabled = enabledMarkets.includes(market); const Icon = market === "domestic" ? Building2 : Globe2; return <button key={market} type="button" role="tab" aria-selected={value === market} disabled={!enabled} onClick={() => onChange(market)} className={`flex items-center justify-center gap-2 rounded-lg py-2.5 text-sm font-bold ${value === market ? "bg-white text-[#173f31] shadow-sm" : enabled ? "text-slate-500" : "cursor-not-allowed text-slate-300"}`}><Icon size={16}/>{market === "domestic" ? "국내" : "해외"}</button>; })}
  </div>;
}

export function SettingsToggle({ checked, onChange, label = "기능 사용", disabled = false }: { checked: boolean; onChange: (checked: boolean) => void; label?: string; disabled?: boolean }) {
  return <button type="button" role="switch" aria-checked={checked} disabled={disabled} onClick={() => onChange(!checked)} className="flex items-center gap-3 disabled:cursor-not-allowed disabled:opacity-50"><span className={`relative h-7 w-12 rounded-full transition ${checked ? "bg-[#173f31]" : "bg-slate-300"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition ${checked ? "left-6" : "left-1"}`}/></span><span className="text-sm font-bold text-slate-700">{label} {checked ? "ON" : "OFF"}</span></button>;
}

export function TimeRangeFields({ start, end, min, max, timeZone, onChange }: { start: string; end: string; min: string; max: string; timeZone: string; onChange: (value: { start: string; end: string }) => void }) {
  const invalid = start >= end;
  return <fieldset><legend className="mb-2 text-xs font-bold text-slate-500">동작 시간</legend><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-500">시작시간<input aria-label="시작시간" type="time" min={min} max={max} value={start} onChange={(event) => onChange({ start: event.target.value, end })} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm text-slate-800 outline-none focus:border-emerald-700"/></label><label className="text-xs text-slate-500">종료시간<input aria-label="종료시간" type="time" min={min} max={max} value={end} onChange={(event) => onChange({ start, end: event.target.value })} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm text-slate-800 outline-none focus:border-emerald-700"/></label></div><p className={`mt-2 text-[11px] ${invalid ? "font-semibold text-rose-600" : "text-slate-400"}`}>{invalid ? "종료시간은 시작시간보다 늦어야 합니다." : `${timeZone} 정규장 ${min}–${max}`}</p></fieldset>;
}

export function ExcludedStockEditor({ query, onQueryChange, onSubmit, searching, results, stocks, onAdd, onRemove, error }: { query: string; onQueryChange: (value: string) => void; onSubmit: (event: FormEvent) => void; searching: boolean; results: ExcludedStock[]; stocks: ExcludedStock[]; onAdd: (stock: ExcludedStock) => void; onRemove: (stock: ExcludedStock) => void; error?: string }) {
  return <div><p className="mb-2 text-xs font-bold text-slate-500">제외종목</p><form onSubmit={onSubmit} className="flex gap-2"><label className="relative flex-1"><span className="sr-only">제외종목 검색</span><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="종목명 또는 종목코드" className="h-11 w-full rounded-xl border border-slate-200 pl-9 pr-3 text-sm outline-none focus:border-emerald-700"/></label><button disabled={!query.trim() || searching} className="rounded-xl bg-[#173f31] px-4 text-sm font-bold text-white disabled:opacity-50">{searching ? "검색 중" : "검색"}</button></form>{error && <p className="mt-2 text-xs text-rose-600">{error}</p>}{results.length > 0 && <ul className="mt-2 max-h-48 divide-y divide-slate-100 overflow-y-auto rounded-xl border border-slate-200">{results.map((stock) => <li key={`${stock.marketCode}-${stock.code}`} className="flex items-center gap-3 px-3 py-2"><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-700">{stock.name}</p><p className="text-[11px] text-slate-400">{stock.code} · {stock.market}</p></div><button type="button" onClick={() => onAdd(stock)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-bold text-emerald-800">추가</button></li>)}</ul>}<div className="mt-3 flex flex-wrap gap-2">{stocks.length === 0 ? <p className="text-xs text-slate-400">등록된 제외종목이 없습니다.</p> : stocks.map((stock) => <span key={`${stock.marketCode}-${stock.code}`} className="inline-flex items-center gap-2 rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-700">{stock.name} ({stock.code})<button type="button" onClick={() => onRemove(stock)} aria-label={`${stock.name} 제외종목 삭제`} className="text-slate-400 hover:text-rose-600"><Trash2 size={14}/></button></span>)}</div></div>;
}

export function SettingsSection({ children }: { children: ReactNode }) { return <section className="rounded-2xl border border-[#dbe4df] bg-white p-5 shadow-[0_8px_24px_rgba(26,55,43,.05)] md:p-6">{children}<StrategyRuntimeStatus/></section>; }

export function PercentField({ label, value, onChange, description }: { label: string; value: number; onChange: (value: number) => void; description?: string }) {
  return <label className="text-xs font-bold text-slate-500">{label} (%)<div className="relative mt-2"><input aria-label={`${label} 퍼센트`} type="number" min="0.01" step="0.01" value={value} onChange={(event) => onChange(Number(event.target.value))} className="h-11 w-full rounded-xl border border-slate-200 px-3 pr-9 text-sm font-normal outline-none focus:border-emerald-700"/><span className="absolute right-3 top-1/2 -translate-y-1/2 text-sm text-slate-400">%</span></div>{description && <span className="mt-1.5 block text-[11px] font-normal leading-4 text-slate-400">{description}</span>}</label>;
}
